name: Build Ragflow for OpenSystemsLab

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
      - 'v*.*.*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: opensystemslab/ragflow

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Free up disk space
      run: |
        echo "Disk usage before cleanup:"
        df -h
        echo "Cleaning up unnecessary files..."
        # Remove unnecessary packages and files
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        # Clean Docker system
        docker system prune -af
        echo "Disk usage after cleanup:"
        df -h

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set image tags
      id: meta
      run: |
        # Generate clean version tags
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          # For tags like v0.20.5 or v0.20.5-opensystemslab, extract just the version number
          VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//' | sed 's/-opensystemslab$//')
          echo "tags=ghcr.io/opensystemslab/ragflow:v${VERSION}" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref }}" == refs/heads/* ]]; then
          # For branches, use branch name
          BRANCH=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9.-]/-/g')
          echo "tags=ghcr.io/opensystemslab/ragflow:${BRANCH}" >> $GITHUB_OUTPUT
        else
          # Fallback
          echo "tags=ghcr.io/opensystemslab/ragflow:${{ github.sha }}" >> $GITHUB_OUTPUT
        fi

    - name: Build and push Docker image (AMD64 only)
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: |
          org.opencontainers.image.source=https://github.com/opensystemslab/ragflow
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ github.ref_name }}
        no-cache: true
        build-args: |
          BUILDPLATFORM=linux/amd64
          TARGETPLATFORM=linux/amd64
          NEED_MIRROR=0
          LIGHTEN=0
        outputs: type=registry
